# This is a basic workflow to help you get started with Actions

name: I-am-Learning-GitHub-Actions
env:
  APPLICATION_NAME    : "It's the first day"
  DEPLOY_PACKAGE_NAME : "of-the-rest-your-life-ver-${{ github.sha }}"

# Controls when the workflow will run
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my-first-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script helloworld
        run: echo "Hello, world!"
      - name: List current folder
        run: ls -la
      - name: Git clone my repo
        uses: actions/checkout@v1
      - name: Execute few commands
        run: |
          echo "Application name: ${{ env.APPLICATION_NAME }}"
          echo "Well, I learned the trade from Piggy Knowles"
          echo "Sing Sing Tommy Shay, boys"
          echo "God used me as a hammer, boys"
          echo "To beat his weary drum today"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script with three echo-command
        run: |
          echo "Hoist that rag!"
          echo "Hoist that rag!"
          echo "Hoist that rag!"
          
  my-second-job:
    runs-on: ubuntu-latest
    needs: [my-first-job]
    steps:
      - name: Print helloworld in Second job
        run: echo "Hello, world from second job!"
        
      - name: Printing Deployment package
        run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
        
      - name: Lets test some packages if they are here 1
        run: aws --version
        
      - name: Lets test some packages if they are here 2
        run: zip
